name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Publish LinkerGenerator to openupm
        uses: butlerlogic/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          root: "UnityResourceGenerator/Assets/AutSoft.UnityResourceGenerator"

      - name: Create GitHub Release
        shell: pwsh
        run: ./build.ps1 CreateGithubRelease --is-ci
